// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TotemAPI.Infrastructure.Persistence;

#nullable disable

namespace TotemAPI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TotemDbContext))]
    [Migration("20260416195843_RemoveEmpresaXSeed")]
    partial class RemoveEmpresaXSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.CartItemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("TenantId", "CartId");

                    b.HasIndex("TenantId", "CartId", "SkuId")
                        .IsUnique();

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.CartRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "UpdatedAt");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.CashRegisterShiftRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedByEmail")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClosingCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpectedCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenedByEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OpeningCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalCashSalesCents")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalSalesCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "OpenedAt");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("cash_register_shifts", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.CategoryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.KitchenSlaRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("PreparationBaseTargetSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueuedTargetSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadyTargetSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId");

                    b.ToTable("kitchen_sla", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.OrderItemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TenantId", "OrderId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.OrderRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comanda")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fulfillment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("InPreparationAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("KitchenStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "UpdatedAt");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.PaymentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PixExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PixPayload")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "OrderId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.SkuRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AveragePrepSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NfeCEan")
                        .HasColumnType("TEXT");

                    b.Property<string>("NfeCEanTrib")
                        .HasColumnType("TEXT");

                    b.Property<string>("NfeCProd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NfeCfop")
                        .HasColumnType("TEXT");

                    b.Property<string>("NfeCofinsCst")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfeCofinsPCofins")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfeCofinsVBc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfeCofinsVCofins")
                        .HasColumnType("TEXT");

                    b.Property<string>("NfeIcmsCst")
                        .HasColumnType("TEXT");

                    b.Property<string>("NfeIcmsModBc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NfeIcmsOrig")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfeIcmsPIcms")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfeIcmsVBc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfeIcmsVIcms")
                        .HasColumnType("TEXT");

                    b.Property<string>("NfePisCst")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfePisPPis")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfePisVBc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfePisVPis")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfeQCom")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfeQTrib")
                        .HasColumnType("TEXT");

                    b.Property<string>("NfeUCom")
                        .HasColumnType("TEXT");

                    b.Property<string>("NfeUTrib")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfeVProd")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfeVUnCom")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NfeVUnTrib")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StockBaseUnit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StockOnHandBaseQty")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TracksStock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CategoryCode");

                    b.HasIndex("TenantId", "NormalizedCode")
                        .IsUnique();

                    b.ToTable("skus", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.SkuStockConsumptionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityBase")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceSkuId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "SkuId");

                    b.HasIndex("TenantId", "SkuId", "SourceSkuId")
                        .IsUnique();

                    b.ToTable("sku_stock_consumptions", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.SkuStockLedgerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeltaBaseQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockAfterBaseQty")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SkuId");

                    b.HasIndex("TenantId", "SkuId", "CreatedAt");

                    b.ToTable("sku_stock_ledger", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.TenantRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.UserRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.CartItemRow", b =>
                {
                    b.HasOne("TotemAPI.Infrastructure.Persistence.CartRow", null)
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.OrderItemRow", b =>
                {
                    b.HasOne("TotemAPI.Infrastructure.Persistence.OrderRow", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TotemAPI.Infrastructure.Persistence.PaymentRow", b =>
                {
                    b.HasOne("TotemAPI.Infrastructure.Persistence.OrderRow", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
